<a href="https://colab.research.google.com/github/Jonas1611/cursomodalmais/blob/main/Modulo_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
preco_weg = 30
while preco_weg < 39:
  print("Ainda não atingiu o preço alvo, espre. o preço atual é :", round(preco_weg,2))
  preco_weg = preco_weg *1.01

else:
  print("Preço alvo atingigo hora de vender! preço da venda ", round(preco_weg,2))

Ainda não atingiu o preço alvo, espre. o preço atual é : 30
Ainda não atingiu o preço alvo, espre. o preço atual é : 30.3
Ainda não atingiu o preço alvo, espre. o preço atual é : 30.6
Ainda não atingiu o preço alvo, espre. o preço atual é : 30.91
Ainda não atingiu o preço alvo, espre. o preço atual é : 31.22
Ainda não atingiu o preço alvo, espre. o preço atual é : 31.53
Ainda não atingiu o preço alvo, espre. o preço atual é : 31.85
Ainda não atingiu o preço alvo, espre. o preço atual é : 32.16
Ainda não atingiu o preço alvo, espre. o preço atual é : 32.49
Ainda não atingiu o preço alvo, espre. o preço atual é : 32.81
Ainda não atingiu o preço alvo, espre. o preço atual é : 33.14
Ainda não atingiu o preço alvo, espre. o preço atual é : 33.47
Ainda não atingiu o preço alvo, espre. o preço atual é : 33.8
Ainda não atingiu o preço alvo, espre. o preço atual é : 34.14
Ainda não atingiu o preço alvo, espre. o preço atual é : 34.48
Ainda não atingiu o preço alvo, espre. o preço atual é : 34.8

In [ ]:
# While

#Imagine que tem disponível 10000  para investir.  A  cada operação sera computado o valor alocado nesta operação (chamaremos de "investimeto_unitario")
#A função imput interage com o usuario, recebendo um objeto ( numérico, string...) e armazenando em uma variável.

  investimento_unitario = 0
  investimento_total = 0
  investimento_limite = 10000

In [ ]:
investimento_unitario = 0
investimento_total = 0
investimento_limite = 10000


while investimento_total <= investimento_limite:
  investimento_unitario = int(input("Quanto deseja investir? "))
  investimento_total = investimento_total + investimento_unitario

else:
  print("\nO limite total para investir foi atingido")
  print("\nVocê excedeu o investimento limite em ", investimento_total - investimento_limite)

print("\nVocê investiu um total de R$", investimento_total)


Quanto deseja investir? 3000
Quanto deseja investir? 2000
Quanto deseja investir? 5000
Quanto deseja investir? 4000

O limite total para investir foi atingido

Você excedeu o investimento limite em  4000

Você investiu um total de R$ 14000


## Alguns outros operadores

### 11.1 Range

In [ ]:
range(0,11)

list(range(0,11))

for i in range(0,11,2):
  print(i)

0
2
4
6
8
10


### 11.2 Enumerate

In [ ]:
lista_ativos = ['PETR4.SA', 'WEGE3.SA', 'MGLU3', 'LREN3.SA', 'RENT3.SA', 'VALE3.SA']

In [ ]:
list(enumerate(lista_ativos))

[(0, 'PETR4.SA'),
 (1, 'WEGE3.SA'),
 (2, 'MGLU3'),
 (3, 'LREN3.SA'),
 (4, 'RENT3.SA'),
 (5, 'VALE3.SA')]

In [ ]:
acao = "PETR4"

for i, j in enumerate(acao):
    print("No índice", i , "o caracter é", j)

No índice 0 o caracter é P
No índice 1 o caracter é E
No índice 2 o caracter é T
No índice 3 o caracter é R
No índice 4 o caracter é 4


In [ ]:
index_count = 0 

for letra in acao:
  print("No índice", index_count, "o caractere é", letra)
  index_count += 1

No índice 0 o caractere é P
No índice 1 o caractere é E
No índice 2 o caractere é T
No índice 3 o caractere é R
No índice 4 o caractere é 4


In [ ]:
acoes = ['PETR4.SA', 'WEGE3.SA', 'MGLU3', 'LREN3.SA', 'RENT3.SA', 'VALE3.SA']

setores = ['Petroleo', 'Motores', 'Varejo', 'Construção', 'Metalurgia']

list(zip(acoes,setores))

[('PETR4.SA', 'Petroleo'),
 ('WEGE3.SA', 'Motores'),
 ('MGLU3', 'Varejo'),
 ('LREN3.SA', 'Construção'),
 ('RENT3.SA', 'Metalurgia')]

In [ ]:

for acao, setor in list(zip(acoes,setores)):
  print('O papel', acao, 'pertence ao setor', setor)

O papel PETR4.SA pertence ao setor Petroleo
O papel WEGE3.SA pertence ao setor Motores
O papel MGLU3 pertence ao setor Varejo
O papel LREN3.SA pertence ao setor Construção
O papel RENT3.SA pertence ao setor Metalurgia


In [ ]:
papel = 'PETR3'
setor = 'petroleo'
f'A {papel} está no setor de {setor}'

'A PETR3 está no setor de petroleo'

In [ ]:
for acao, setor in list(zip(acoes,setores)):
  print(f'O papel {acao} pertence ao setor {setor}')

O papel PETR4.SA pertence ao setor Petroleo
O papel WEGE3.SA pertence ao setor Motores
O papel MGLU3 pertence ao setor Varejo
O papel LREN3.SA pertence ao setor Construção
O papel RENT3.SA pertence ao setor Metalurgia


In [ ]:
'VIVR3' in acoes

False

In [ ]:
"RENT3.SA" in acoes

True

### 11.4 Randint


In [3]:
from random import randint, shuffle 

randint(0,100)

49

In [4]:
list_rand = []

for i in range(0,10):
  list_rand.append(randint(0,100))

In [5]:
list_rand

[2, 34, 52, 95, 29, 93, 62, 18, 69, 56]

In [6]:
shuffle(list_rand)
list_rand

[52, 2, 62, 29, 93, 34, 69, 56, 18, 95]

In [9]:
list_rand.sort()

list_rand


[2, 18, 29, 34, 52, 56, 62, 69, 93, 95]

In [10]:
list_rand.reverse()

list_rand

[95, 93, 69, 62, 56, 52, 34, 29, 18, 2]

In [13]:
min(list_rand)



2

In [14]:
max(list_rand)

95

In [18]:
acao = input("Insira a ação que deseja comprar: ")

Insira a ação que deseja comprar: PETR4


In [20]:
acao


'PETR4'

In [21]:
print(f'O cliente desja comprar a ação {acao}')

O cliente desja comprar a ação PETR4


# 12 List Comprehension (Compreensão de lista)


In [34]:
acao = 'MGLU3'

In [35]:
lista_caracteres = []

In [36]:
for i in acao:
  lista_caracteres.append(i)

## Aula 04

In [ ]:
from random import randint, shuffle

In [ ]:
randint(0,100)

64

In [ ]:
list_rand = []

for i in range(0,10):
  list_rand.append(randint(0,100))

In [ ]:
list_rand

[11, 100, 33, 51, 87, 76, 17, 81, 95, 48]

In [ ]:
list_rand.reverse()



In [ ]:
list_rand.sort()

In [ ]:
list_rand

[11, 17, 33, 48, 51, 76, 81, 87, 95, 100]

In [ ]:
list_rand.reverse()

In [ ]:
list_rand

[100, 95, 87, 81, 76, 51, 48, 33, 17, 11]

In [ ]:
shuffle(list_rand)

In [ ]:
list_rand

[87, 81, 17, 76, 33, 100, 95, 48, 51, 11]

In [ ]:
min(list_rand)

11

In [ ]:
max(list_rand)

100

## 12 List Comprehension

In [ ]:
acao = 'MGLU3'

In [ ]:
lista_caracteres = []

for caractere in acao:
  lista_caracteres.append(caractere)

lista_caracteres*2

['M', 'G', 'L', 'U', '3', 'M', 'G', 'L', 'U', '3']

In [48]:
ativos = ['MGLU' , 'VALE' , 'WEGE' , 'LREN']



novos_ativos = []

for ativo in ativos:
  novos_ativos.append(ativo - '3')

In [53]:
novos_ativos

[]

In [54]:
[ativo + '3' for ativo in ativos] 

['MGLU3', 'VALE3', 'WEGE3', 'LREN3']

In [ ]:
range(1,11)

list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
[num**2 for num in range(0,11)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

**13. Funções e métodos**


In [ ]:
def tempo_hoje():
  print('Hoje faz sol')

In [ ]:
tempo_hoje()

Hoje faz sol


In [56]:
def soma_numero(num1, num2):
  soma = num1 + num2
  return soma

In [57]:
novo_objeto = soma_numero(2,3)

In [58]:
novo_objeto

5

In [60]:
novo_objeto = soma_numero(3050 , 1000)

In [61]:
novo_objeto

4050

In [73]:
def preco(acao):

  '''Essa Função retorna a cotação em tempo real'''
  
  if(acao == 'PETR4'):
    print('O preço do papel agora é R$ 30,89')
  elif (acao == 'VALE3'):
    print('O preço do papel agora é R$ 48,50')
  elif (acao == 'MGLU3'):
    print('O preço do papel agora é R$ 8,50')
  else: 
    print('Papel desconhecido')

In [74]:
preco('')

Papel desconhecido


***Metodo***

In [75]:
numeros = [1, 2 , 3 , 4 , 5]

In [78]:
numeros.append(10)

In [79]:
numeros

[1, 2, 3, 4, 5, 5, 10]

# 14. Funções embutidas 



## 14.1 Map

In [84]:
def potencia(num, pot =2):
  return num**pot

In [85]:
potencia(9)

81

In [88]:
lista_numeros = [1,2,3,4,5]

In [90]:
list(map(potencia, lista_numeros))

[1, 4, 9, 16, 25]

## 14.2 Filter

In [101]:
def checar_par(num):
  return num % 2 == 0

In [102]:
checar_par(2)

True

In [103]:
checar_par(5)

False

In [107]:
list(filter(checar_par, lista_numeros))

[2, 4]

# 15. Funcções Lambda - Funcões Anônimas


In [108]:
def quadrado(num):
  return num**2

In [109]:
quadrado(4)

16

In [112]:
quadrado_lambda = lambda num: num**2

In [113]:
quadrado_lambda(4)

16

In [114]:
list(filter(lambda num:  num%2 == 0, lista_numeros))

[2, 4]

# 16. Escopo das Variáveis

 

# 17. Args

In [17]:
def soma_varios(*bet):
  soma = sum((bet))
  return soma

In [20]:
soma_varios(5,10,20,40,3,-5)


73

# 18.kwqrgs

In [30]:
def compra_de_acoes(**kwargs):
  if 'acao' in kwargs:
    print('A ação comprada foi', kwargs['acao'])
  else:
    print('o cliente não investe em ações')

In [31]:
compra_de_acoes(acao = 'MGLU3')

A ação comprada foi MGLU3


In [32]:
compra_de_acoes()

o cliente não investe em ações


In [45]:
def montagem_posicao(*args, **kwargs):
  if 'acao' and 'lote' in kwargs:
    print('O cliente montou uma posição', ' e '.join(kwargs['acao']))
    print('Ele comprou', ' e '.join(args), 'papéis respectivamente')
    print('Todas elas foram compradas no lote', kwargs['lote'])

In [46]:
montagem_posicao('100','200','300', acao = ('VALE3', 'MGLU3', 'PTRO3'), lote = 'inteiro')

O cliente montou uma posição VALE3 e MGLU3 e PTRO3
Ele comprou 100 e 200 e 300 papéis respectivamente
Todas elas foram compradas no lote inteiro


# 19.Trabalhando com Bibliotecas


In [2]:
import numpy as np
import pandas as pd

In [49]:
a = np.zeros(5)

In [50]:
a

array([0., 0., 0., 0., 0.])

In [51]:
a.shape

(5,)

In [61]:
a.shape = (5,1)

In [54]:
a.shape

(5, 1)

In [62]:
a

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [64]:
b = np.ones(10)

In [65]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
c = np.empty(3)

In [5]:
c

array([0.75, 0.75, 0.  ])

In [6]:
d = np.linspace(3, 15 , 10)

In [7]:
d

array([ 3.        ,  4.33333333,  5.66666667,  7.        ,  8.33333333,
        9.66666667, 11.        , 12.33333333, 13.66666667, 15.        ])

In [8]:
listas_de_litas = [[1,2,3,4,5],[6,7,8,9,10]]

In [9]:
h = np.array(listas_de_litas)

In [10]:
h

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
np.random.seed(0)

In [24]:
np.random.seed(0)
np.random.randint(10, size = 6)

array([5, 0, 3, 3, 7, 9])

In [25]:
a = np.random.randint(5, size = 10)

In [26]:
a

array([3, 2, 4, 0, 0, 4, 2, 1, 0, 1])

In [27]:
b = np.random.randint(5, size = 10)

In [28]:
b

array([1, 0, 1, 4, 3, 0, 3, 0, 2, 3])

In [30]:
a + b

array([4, 2, 5, 4, 3, 4, 5, 1, 2, 4])

In [31]:
np.subtract(a,b)

array([ 2,  2,  3, -4, -3,  4, -1,  1, -2, -2])

In [32]:
np.add(a,b)

array([4, 2, 5, 4, 3, 4, 5, 1, 2, 4])

In [33]:
np.multiply(a,b)

array([3, 0, 4, 0, 0, 0, 6, 0, 0, 3])

In [34]:
np.divide(a,b)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([3.        ,        inf, 4.        , 0.        , 0.        ,
              inf, 0.66666667,        inf, 0.        , 0.33333333])

# 19.3  Pandas